#include "FadedNativeGameplayTags.h"

//Cover
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER, "Faded.Abilities.Movement.Cover", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER_ABILITY, "Faded.Abilities.Movement.Cover.Ability", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER_ENTER, "Faded.Abilities.Movement.Cover.Enter", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER_EXIT, "Faded.Abilities.Movement.Cover.Exit", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER_FIRE, "Faded.Abilities.Movement.Cover.Fire", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER_BLINDFIRE, "Faded.Abilities.Movement.Cover.BlindFire", "");
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_COVER_MOVE_TO_ADJACENT, "Faded.Abilities.Movement.Cover.MoveToAdajacent", "");

// Dodge
UE_DEFINE_GAMEPLAY_TAG_COMMENT(TAG_ABILITIES_MOVEMENT_DODGE, "Faded.Abilities.Movement.Dodge", "");